# Generated by Django 3.0.7 on 2020-09-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_auto_20200912_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='fpo_registeration',
            name='fpo_description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fpo_registeration',
            name='fpo_mobile1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='fpo_registeration',
            name='fpo_mobile2',
            field=models.IntegerField(null=True),
        ),
    ]
