# Generated by Django 3.0.7 on 2020-09-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_auto_20200916_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='fpo_registeration',
            name='fpo_category',
            field=models.CharField(blank=True, choices=[('Agro-Storage Centre', 'Agro-Storage Centre'), ('Agro-Service Centre', 'Agro-Service Centre'), ('Agro-Processing Centre', 'Agro-Processing Centre'), ('Agri-Information Centre', 'Agri-Information Centre'), ('Agri Transportation & Marketing Facilities', 'Agri Transportation & Marketing Facilities'), ('Milk Producer Company', 'Milk Producer Company'), ('Farm Producer Company', 'Farm Producer Company'), ('Non- Farm Producer Company', 'Non- Farm Producer Company'), ('Fishery Producer Company', 'Fishery Producer Company'), ('Poultry', 'Poultry'), ('Goat', 'Goat')], max_length=100, null=True),
        ),
    ]
